
apiVersion: v11
kind: Config

clusters:
- name: k3s-cluster
  cluster:
    server: https://192.168.21.100:6443 # est l'adresse du control-plane
    certificate-authority-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUc2T29sdWtYbzRVb1ZHTWJwR2NXZVhDK09jdTRpV0NNMzJOU3F0b0YzVnlvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFSFpmT0E1bS9JOG5majVkV1E4QnVvTXM3K2wzVVU5MHpVcUVHYlplZlpSV094ci9LRFhragpDa1N3R1NmSzNpb0RidWtRWUp1eE1KWlJEb2llOURYSm53PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=

users:
- name: etudiant
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ino5NUJFRXNvNmdUcjYtV2ZMdF9tVDZuSnRXNUVmR3FSN0pjRUZvbC1CdlkifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzc1ODQ5MzI1LCJpYXQiOjE3NzU4NDU3MjUsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYzM5MDQwY2MtMTA3My00NjE4LWI5YTUtMzVlMzQ5MWFiNzBlIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZXYiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZXR1ZGlhbnQtc3J2YWNjb3VudCIsInVpZCI6ImI0MzZmNzZkLTJhZDgtNDdjMC1iNTBhLTFkY2YxODBiMDBjYSJ9fSwibmJmIjoxNzc1ODQ1NzI1LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGV2OmV0dWRpYW50LXNydmFjY291bnQifQ.eKP6cAzkfQB9lL2_LYWbEIFoaV5XqZzWiXzDBV8cbj7a0yx2zeeud-b3uV8cq5lYdH9kYiY6p6dqQ_kKM-z0cLxbU0iRh_55hCGz2ZmJmlL50Fot2kLnhoPLr1WOjTKMgJWs2LWystP1lOUoAc0UQRiOT8NEDOR5etNgJH3Izaxm9dtenhbjFZpu9G00IERAcuFBZEHlGPxxh8k3hFT1B6QCmOXvsVLX21SV3Q8DcvKIwasyxOLCGtbEo_qYXH3IACgT9Y2eLGfyHOYeAWZT729KMX_q4Y9kHp2hZwoSIp_IG-FvKTnfbtHo_DSjKIqUx7LtmGF-A9CgBijFCSQY7g

contexts:
- name: etudiant-context
  context:
    cluster: k3s-cluster
    user: etudiant
    namespace: dev

current-context: etudiant-context
