apiVersion: v1
kind: Config

clusters:
- name: k3s-cluster
  cluster:
    server: https://192.168.21.100:6443 # est l'adresse du control-plane
    certificate-authority-data: <CA_BASE64>

users:
- name: etudiant
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ino5NUJFRXNvNmdUcjYtV2ZMdF9tVDZuSnRXNUVmR3FSN0pjRUZvbC1CdlkifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzc1ODU3MDE3LCJpYXQiOjE3NzU4NTM0MTcsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiNDFmOWI3MGMtZGI1Ni00ODFjLWI3YTktYjYxNjgzMjFlM2FjIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZXYiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZXR1ZGlhbnQtc3J2YWNjb3VudCIsInVpZCI6ImI0MzZmNzZkLTJhZDgtNDdjMC1iNTBhLTFkY2YxODBiMDBjYSJ9fSwibmJmIjoxNzc1ODUzNDE3LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGV2OmV0dWRpYW50LXNydmFjY291bnQifQ.sgZdWEP_zJczk89iU6VrziUIGRqX90xgyt4Ps-d0fv5lhgW4GUCB9ctmEvFtyOB3y778J5l_EN7CrQkoEOwF3xNBPAq4HLqVih6JgswwiJct4q7MmMb1PXSNcI6EUH4NNfZe_WNULuPCr203PpqBsdveLYZOnUbeXKw9AfXWs_iQxEet3s6zhwAtdo6rNvJtQn506xCQ6vmySBc25EF206iKzml7krkBq8qAOY2WUSUeepqvhsF0WnjqufcK94w3DdzP_r96Heg1wrDZtl7M7sOKgdauz0i0sN6jfHbDId71R8jN6_k6rwcD8pU0xGATLPYEW9616WkK_KYPTE8AJQ

contexts:
- name: etudiant-context
  context:
    cluster: k3s-cluster
    user: etudiant
    namespace: dev

current-context: etudiant-context