apiVersion: v1
kind: Config

clusters:
- name: k3s-cluster
  cluster:
    server: https://192.168.21.100:6443 # est l'adresse du control-plane
    insecure-skip-tls-verify: true

users:
- name: etudiant
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ino5NUJFRXNvNmdUcjYtV2ZMdF9tVDZuSnRXNUVmR3FSN0pjRUZvbC1CdlkifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzc3MDUzOTU4LCJpYXQiOjE3NzcwNTAzNTgsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYTU0ODJjNTctZjI3Ny00OGZmLTlkNWMtNmYyZTI4ZmI4OTVhIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZXYiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZXR1ZGlhbnQtc3J2YWNjb3VudCIsInVpZCI6ImI0MzZmNzZkLTJhZDgtNDdjMC1iNTBhLTFkY2YxODBiMDBjYSJ9fSwibmJmIjoxNzc3MDUwMzU4LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGV2OmV0dWRpYW50LXNydmFjY291bnQifQ.ViWHoM4DWX46Ou7-JbyOc3fuq4Xng9TvGgXP3tRd8B_8dM59OBid3rCjkhit58bWsN--cUqRs6I27HFWH0R_q1b7MNmo7Koscm_Hd2R8Lh3YbIVABOSkdGq-I8lyM4noz5HTuVdV9aJKVjphYXuazUMxETCaKIhTBFaOyAB3uyH6tE14P9RCo79hUZwdwLyI4CQpX3nW0dPQ0IBMRNmi5jrdzFCumJKmHMx34iEh8-Mot5hi9DxvwUt0tT5017Rp7BB_e1BHA7-zgxUZ3FnhIOUWXEWyHzJdPoJRyXhzHYUQ17DmJcwmfpsIKaQuYPg09htBg1pMh-KbTP2CcoIk_Q.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzc2MTAyNTI3LCJpYXQiOjE3NzYwOTg5MjcsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiZGEwNTVhYTItMTRjNC00ZjUwLTk1NjYtMjJjNjE1ZWUyZmEzIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZXYiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZXR1ZGlhbnQtc3J2YWNjb3VudCIsInVpZCI6ImI0MzZmNzZkLTJhZDgtNDdjMC1iNTBhLTFkY2YxODBiMDBjYSJ9fSwibmJmIjoxNzc2MDk4OTI3LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGV2OmV0dWRpYW50LXNydmFjY291bnQifQ.nOdTAagydiCpAz3hpi_V9NiNV_N1JvwtuSpgrcrW51TAs-WdDGp2FlphAyKoKDFqGrlh29WPlv4Rjurn9MY08z-CZkCi3EgqxDl4PUZK5uvkY8P7r1YddLdsfA3q3NACLDrALqxu0DXONGzwH3nvcpvfnCrjIkZRY7zikV-YNbiJR_ueGZn8_CLY5XmHuTOVUcPiivYGoNsmTb7Rkr9fnxdmtm3ezqK_j6p-wtjKxTtp2UKpgUQcyJU2PD-Vvj15Um-V8uQNgyNcKU6yXdUF8S6bEnBQT6LbDSzebIm6QV-7-JHCN_T8DBQDmI8UN1lp5n6MOM19hjObI6IlkRHOXw

contexts:
- name: etudiant-context
  context:
    cluster: k3s-cluster
    user: etudiant
    namespace: dev

current-context: etudiant-context

  
